-- Insights and Workflows System
-- This migration creates tables for Insight Agent insights and workflows

-- Insights table
-- Stores insights generated by agents or the Insight Agent itself
CREATE TABLE IF NOT EXISTS insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Source and categorization
  source TEXT NOT NULL CHECK (source IN ('aloha', 'sync', 'studio', 'insight_agent', 'system', 'manual')),
  category TEXT NOT NULL CHECK (category IN ('productivity', 'communication', 'finance', 'sales', 'risk', 'ops', 'misc')),
  severity TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  
  -- Content
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  
  -- Time range (for rollup insights)
  time_range TEXT, -- e.g., 'this week', 'today', 'last month'
  
  -- Tags and metadata
  tags JSONB DEFAULT '[]'::jsonb, -- Array of strings
  metadata JSONB DEFAULT '{}'::jsonb,
  
  -- Actions (recommended actions with type + payload)
  actions JSONB DEFAULT '[]'::jsonb, -- Array of action objects
  
  -- Read/dismiss tracking
  is_read BOOLEAN DEFAULT FALSE,
  dismissed_at TIMESTAMP WITH TIME ZONE,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Workflows table (fix missing table)
CREATE TABLE IF NOT EXISTS workflows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Basic info
  name TEXT NOT NULL,
  description TEXT,
  enabled BOOLEAN DEFAULT TRUE,
  
  -- Trigger configuration
  trigger TEXT NOT NULL CHECK (trigger IN ('email.received', 'calendar.event.created', 'metric.updated', 'time-based', 'user-initiated', 'insight.generated')),
  trigger_config JSONB DEFAULT '{}'::jsonb, -- Additional trigger configuration
  
  -- Condition (optional)
  condition JSONB, -- { field, operator, value }
  
  -- Actions
  actions JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of action strings
  
  -- Execution tracking
  last_run_at TIMESTAMP WITH TIME ZONE,
  run_count INTEGER DEFAULT 0,
  
  -- Metadata
  metadata JSONB DEFAULT '{}'::jsonb,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insight Briefs table (store generated briefs)
CREATE TABLE IF NOT EXISTS insight_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Brief configuration
  range TEXT NOT NULL CHECK (range IN ('daily', 'weekly', 'monthly')),
  
  -- Brief content (structured JSON)
  brief_data JSONB NOT NULL, -- Stores the full brief structure
  
  -- Timestamps
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_insights_user_id ON insights(user_id);
CREATE INDEX IF NOT EXISTS idx_insights_created_at ON insights(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_insights_source ON insights(source);
CREATE INDEX IF NOT EXISTS idx_insights_category ON insights(category);
CREATE INDEX IF NOT EXISTS idx_insights_severity ON insights(severity);
CREATE INDEX IF NOT EXISTS idx_insights_is_read ON insights(is_read);
CREATE INDEX IF NOT EXISTS idx_insights_user_created ON insights(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_workflows_user_id ON workflows(user_id);
CREATE INDEX IF NOT EXISTS idx_workflows_enabled ON workflows(enabled);
CREATE INDEX IF NOT EXISTS idx_workflows_trigger ON workflows(trigger);

CREATE INDEX IF NOT EXISTS idx_insight_briefs_user_id ON insight_briefs(user_id);
CREATE INDEX IF NOT EXISTS idx_insight_briefs_range ON insight_briefs(range);
CREATE INDEX IF NOT EXISTS idx_insight_briefs_generated_at ON insight_briefs(generated_at DESC);

-- RLS Policies
ALTER TABLE insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE insight_briefs ENABLE ROW LEVEL SECURITY;

-- Insights policies
CREATE POLICY "Users can view their own insights"
  ON insights FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own insights"
  ON insights FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own insights"
  ON insights FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own insights"
  ON insights FOR DELETE
  USING (auth.uid() = user_id);

-- Workflows policies
CREATE POLICY "Users can view their own workflows"
  ON workflows FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own workflows"
  ON workflows FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own workflows"
  ON workflows FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own workflows"
  ON workflows FOR DELETE
  USING (auth.uid() = user_id);

-- Insight Briefs policies
CREATE POLICY "Users can view their own briefs"
  ON insight_briefs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own briefs"
  ON insight_briefs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own briefs"
  ON insight_briefs FOR DELETE
  USING (auth.uid() = user_id);




