-- ============================================================================
-- Migration: 20250127000000_studio_reports_schema.sql
-- ============================================================================
-- Add weekly reports table for Studio insights
-- 
-- This migration adds:
-- 1. studio_reports - Stores LLM-generated weekly reports
-- 2. Indexes for efficient queries
-- ============================================================================

-- ============================================================================
-- 1. CREATE studio_reports TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.studio_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  summary_markdown TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Ensure one report per workspace per period (prevent duplicates)
  CONSTRAINT unique_workspace_period UNIQUE (workspace_id, period_start, period_end)
);

-- Index for workspace queries
CREATE INDEX IF NOT EXISTS idx_studio_reports_workspace_id
  ON public.studio_reports (workspace_id);

-- Index for date range queries
CREATE INDEX IF NOT EXISTS idx_studio_reports_period
  ON public.studio_reports (workspace_id, period_start DESC, period_end DESC);

-- ============================================================================
-- 2. ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.studio_reports ENABLE ROW LEVEL SECURITY;

-- Reports policies
CREATE POLICY "Workspace members can view their reports" ON public.studio_reports
  FOR SELECT USING (
    auth.uid() IN (
      SELECT user_id FROM public.workspace_members 
      WHERE workspace_id = public.studio_reports.workspace_id
    )
  );

CREATE POLICY "Workspace members can insert their reports" ON public.studio_reports
  FOR INSERT WITH CHECK (
    auth.uid() IN (
      SELECT user_id FROM public.workspace_members 
      WHERE workspace_id = public.studio_reports.workspace_id
    )
  );

-- ============================================================================
-- 3. ADD COMMENTS
-- ============================================================================

COMMENT ON TABLE public.studio_reports IS 'Weekly reports generated by LLM for Studio insights';
COMMENT ON COLUMN public.studio_reports.period_start IS 'Start of the reporting period (typically Monday)';
COMMENT ON COLUMN public.studio_reports.period_end IS 'End of the reporting period (typically Sunday)';
COMMENT ON COLUMN public.studio_reports.summary_markdown IS 'LLM-generated markdown report with insights and recommendations';

